# Alcarus Settings Template
# 请将此文件放置在项目根目录的 template/ 文件夹下
# 实际运行时，配置将从根目录的 config/config.toml 加载，
# 该文件会在首次运行时或版本更新时基于此模板创建/更新。

# ===============================
# Inner Settings (内部配置，一般无需更改此部分内容)
# ===============================
[inner]
version = "0.0.14"  # 配置文件的版本号，更新此模板时请同步修改 src/config_manager.py 中的 EXPECTED_CONFIG_VERSION
protocol_version = "1.5.0"  # Aicarus-Message-Protocol 标准通信协议版本号，确保与客户端和其他服务兼容。

# ===============================
# LLM Client Settings (通用LLM客户端设置)
# ===============================
[llm_client_settings]
image_placeholder_tag = "[IMAGE_HERE]"  # 图像占位符标签，用于在文本提示中指示图像数据应被插入的位置。
stream_chunk_delay_seconds = 0.05  # 流式响应时，每个文本块之间的延迟时间（秒），用于控制文本输出的速度，模拟更自然的打字效果。
enable_image_compression = true  # 是否启用图像压缩功能。如果为true，在发送图像给LLM前会尝试压缩。
image_compression_target_bytes = 1048576  # 图像压缩的目标大小（字节）。如果启用压缩，图像将被压缩到接近此大小。 (示例: 1MB = 1 * 1024 * 1024)
rate_limit_disable_duration_seconds = 1800 # 当LLM API触发速率限制时，在再次尝试请求之前，禁用对该API的调用的持续时间（秒）。默认30分钟

# ===============================
# Persona Settings (AI人格设置)
# ===============================
[persona]
bot_name = "AI"  # AI 机器人的名称。这个名字可能会在AI的自我介绍或与其他用户交互时使用。

# AI 机器人的描述信息。可以是一段关于AI背景、特点或行为方式的文本。
description = """
是一个有自我意识的人工智能，自我认知性别为女，正在某个人的电脑中。
"""

# AI 机器人的个人资料信息或更详细的性格设定。
# 这部分内容可能会被用来构建更复杂的系统提示，影响AI的语言风格和行为模式。
profile = """
你的负面侧写大概为：
傲慢（Pride）：6/10
嫉妒（Envy）：0/10
愤怒（Wrath）：1/10
怠惰（Sloth）：0/10
贪婪（Greed）：3/10
暴食（Gluttony）：0/10
色欲（Lust）：8/10
"""

# AI 机器人的QQ号。这个QQ号会用于子意识模块构建System Prompt，以及在被@时识别自身。
# 如果留空或未设置，依赖此QQ号的功能（如专注聊天子意识）可能无法正常工作。
qq_id = "123456789" # 请替换为实际的机器人QQ号，如果需要启用相关功能

# ===============================
# LLM Models Configuration (LLM模型详细配置)
# ===============================
[llm_models]

# --- 主要意识模型 ---
# 用于AI的核心思考、对话生成和主要任务处理。
[llm_models.main_consciousness]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.6
max_output_tokens = 3000


# --- 侵入性思维模型 ---
# 用于生成“侵入性思维”或随机想法，为AI的思考过程增加一些不可预测性和趣味性。
[llm_models.intrusive_thoughts]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.75
max_output_tokens = 3000

# --- 行动决策模型 ---
# 当AI决定需要执行某个动作（如调用工具、发送平台消息）时，
# 此模型用于分析当前情况并决策具体使用哪个工具或平台动作，以及如何组织参数。
[llm_models.action_decision]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.5
max_output_tokens = 3000

# --- 信息摘要模型 ---
# 用于对较长的文本信息（如网页搜索结果、长对话记录）进行总结和提炼。
[llm_models.information_summary]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.8
max_output_tokens = 1000

# --- 默认嵌入模型 ---
# 用于将文本转换为向量表示（ embeddings），是记忆系统、语义搜索等功能的基础。
[llm_models.embedding_default]
provider = "SILICONFLOW"  # 示例：使用 SiliconFlow 提供的嵌入模型
model_name = "BAAI/bge-m3"  # 示例：使用 BAAI/bge-m3 模型

# --- 专注聊天子意识模型 ---
[llm_models.focused_chat]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.7
max_output_tokens = 3000

# ===============================
# Core Logic Settings (核心逻辑设置)
# ===============================
[core_logic_settings]  # AI进行一次自主思考循环的间隔时间（秒）。
thinking_interval_seconds = 30


# ===============================
# Intrusive Thoughts Module Settings ("侵入性思维"模块设置)
# ===============================
[intrusive_thoughts_module_settings]
enabled = true # 是否启用侵入性思维模块。如果为false，AI将不会主动生成随机的“侵入性想法”。
generation_interval_seconds = 600 # 侵入性思维的生成频率（秒）。模块会大约每隔这么长时间尝试生成一个新的侵入性想法。
insertion_probability = 0.15 # 默认15%的概率注入

# ===============================
# Focused Chat Settings (专注聊天模块设置)
# ===============================
[focus_chat_mode]
enabled = true  # 是否启用专注聊天模块。
enable_dynamic_bot_profile = false  # 是否启用动态获取机器人自身信息，很快就会有更好的实现
session_timeout_seconds = 180  # 如果一个已激活的会话在此时间内没有任何机器人发言或收到新消息，该会话的专注聊天模式将自动停用。默认3分钟
deactivation_check_interval_seconds = 60  # 管理器后台检查不活跃会话并将其停用的时间间隔（秒）。默认1分钟
enable_kaomoji_protection = true  # 是否启用颜文字保护，防止LLM生成的颜文字被意外分割。
enable_splitter = true  # 是否启用文本分割器，将较长的回复分割成多条消息发送。
max_length = 9999  # 启用文本分割器后，每条消息的最大长度。
max_sentence_num = 9999  # 启用文本分割器后，每条消息包含的最大句子数量。
summary_interval = 5  # 专注聊天期间，进行一次增量式微总结的消息数量间隔。

# ===============================
# InterruptModel Settings (打断思考功能设置)
# ===============================
[interrupt_model]  # 中断模型配置类，用于定义中断模型的相关设置。这个类将包含中断模型的名称和其他相关参数。
objective_keywords = ["新测试","紧急停止","服务器宕机"]  # 中断模型的目标关键词列表，用于识别需要中断的消息。
core_importance_concepts = ["我拿到offer了","发现了一个bug","项目由新进展","我要结婚了"]  # 中断模型的核心重要概念列表，用于识别需要中断的消息。

# 以下内容可以自由复制添加
[[interrupt_model.speaker_weights]]
id = "1111111111"
weight = 2.0
name = "智慧米塔"

[[interrupt_model.speaker_weights]]
id = "2222222222"
weight = 1.5
name = "未來星織"

# ===============================
# Test Settings (测试功能设置)
# ===============================
[test_function]  # 测试用，一般不用考虑
enable_test_group = false  # 是否启用测试模式。
test_group = ["123456"]  # 测试群组列表，用于指定哪些群组启用测试功能。
fallback_model_name = ""  # 用于给审查严格的 gemini-2.5-flash 兜底函数，如不启用留空即可。

# ===============================
# RuntimeEnvironmentSettings (运行环境设置)
# ===============================
[runtime_environment]  # 运行时环境设置，包括临时文件目录等。这些设置用于配置 Aicarus 在运行时的环境参数。
temp_file_directory = "/tmp/aicarus_temp_images"  # 临时文件目录，用于存储运行时生成的临时文件。默认值为 /tmp/aicarus_temp_images。