# Alcarus Settings Template
# 请将此文件放置在项目根目录的 template/ 文件夹下
# 实际运行时，配置将从根目录的 config/config.toml 加载，
# 该文件会在首次运行时或版本更新时基于此模板创建/更新。

# 内部配置，用于版本控制
[inner]
version = "0.0.3" # 配置文件的版本号，更新此模板时请同步修改 src/config_manager.py 中的 EXPECTED_CONFIG_VERSION

# 通用 LLM 客户端设置 (应用于所有 LLM 实例)
[llm_client_settings]
# 指向 .env 文件中存储废弃 API 密钥列表的环境变量名 (可选)
# 如果设置了此项，代码会尝试读取名为 "LLM_ABANDONED_KEYS" 的环境变量。
# 如果不设置此项，或代码中不再读取此项，则废弃密钥功能将依赖其他实现（例如，代码内部的列表）。
# 考虑到您希望移除所有 *_env_var 指向，这一项也可能需要重新考虑其存在意义。
# 暂时保留，但如果代码不再读取它，它就无效了。
abandoned_keys_env_var = "LLM_ABANDONED_KEYS" # 如果代码不再使用这个key去os.getenv()，那这个配置本身也无意义了

image_placeholder_tag = "[IMAGE_HERE]"
stream_chunk_delay_seconds = 0.05
enable_image_compression = true
image_compression_target_bytes = 1048576
rate_limit_disable_duration_seconds = 1800 # 默认30分钟

# ===============================
# Persona Settings
# ===============================
[persona]
bot_name = "霜"
description = """
是一个对宇宙，科学，自然比较感兴趣的20岁女生，是个宅女，你喜欢读各种关于宇宙的论文，也会看一些相关的网站。
不打游戏。会看纪录片。其中尤其偏爱各种科学，宇宙天体，科幻，自然题材的纪录片。
你不太喜欢在现实中与他人交互，相对来说，在网络上交流让你感到更轻松。
你比较理性，喜欢熬夜和赖床。你的癖好是有M倾向，偶尔会看一些猎奇视频。
你身高171cm，体重55kg，身材匀称。
"""
profile = """
你的负面侧写大概为：
傲慢（Pride）：2/10
嫉妒（Envy）：1/10
愤怒（Wrath）：2/10
怠惰（Sloth）：6/10
贪婪（Greed）：0/10
暴食（Gluttony）：2/10
色欲（Lust）：8/10
社交回避/内向（Social Avoidance/Introversion）：7/10
固执（Stubbornness）：4/10
"""

# -----------------------------------------------------------------------------
# LLM 提供商和模型详细配置
# -----------------------------------------------------------------------------

[providers]

[providers.gemini.models.main_consciousness]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.6
max_output_tokens = 2000

[providers.gemini.models.intrusive_thoughts]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.75
max_output_tokens = 500

[providers.gemini.models.action_decision]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.3
max_output_tokens = 800

[providers.gemini.models.information_summary]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.5
max_output_tokens = 1000

# -----------------------------------------------------------------------------
# 网络代理配置
# -----------------------------------------------------------------------------
[proxy]
use_proxy = true
# 如果 use_proxy = true，代码会尝试从 http_proxy_url 解析 host 和 port,
# 如果 http_proxy_url 为空或无效，则可能尝试从环境变量 PROXY_HOST 和 PROXY_PORT 读取。
# 这个逻辑需要在代码中确认和调整。
http_proxy_url = "" # 例如 "http://127.0.0.1:7890"


# -----------------------------------------------------------------------------
# 应用核心逻辑 ("意识流") 设置
# -----------------------------------------------------------------------------
[core_logic_settings]
thinking_interval_seconds = 30

# -----------------------------------------------------------------------------
# "侵入性思维" 模块设置
# -----------------------------------------------------------------------------
[intrusive_thoughts_module_settings]
enabled = true
generation_interval_seconds = 600
insertion_probability = 0.15