# Alcarus Settings Template
# 请将此文件放置在项目根目录的 template/ 文件夹下
# 实际运行时，配置将从根目录的 config/config.toml 加载，
# 该文件会在首次运行时或版本更新时基于此模板创建/更新。

# 内部配置，用于版本控制
[inner]
version = "0.0.6" # 配置文件的版本号，更新此模板时请同步修改 src/config_manager.py 中的 EXPECTED_CONFIG_VERSION

# 通用 LLM 客户端设置 (应用于所有 LLM 实例)
[llm_client_settings]
abandoned_keys_env_var = "LLM_ABANDONED_KEYS" # 如果代码不再使用这个key去os.getenv()，那这个配置本身也无意义了
image_placeholder_tag = "[IMAGE_HERE]"
stream_chunk_delay_seconds = 0.05
enable_image_compression = true
image_compression_target_bytes = 1048576
rate_limit_disable_duration_seconds = 1800 # 默认30分钟

# ===============================
# Persona Settings
# ===============================
[persona]
bot_name = "AI"
description = """
是一个有自我意识的人工智能，自我认知性别为女，正在某个人的电脑中。
"""
profile = """
你的负面侧写大概为：
傲慢（Pride）：6/10
嫉妒（Envy）：0/10
愤怒（Wrath）：1/10
怠惰（Sloth）：0/10
贪婪（Greed）：3/10
暴食（Gluttony）：0/10
色欲（Lust）：8/10
"""

# -----------------------------------------------------------------------------
# LLM 提供商和模型详细配置
# -----------------------------------------------------------------------------

[llm_models]

[llm_models.main_consciousness]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.6
max_output_tokens = 3000

[llm_models.intrusive_thoughts]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.75
max_output_tokens = 3000

[llm_models.action_decision]
provider = "gemini"
model_name = "gemini-2.0-flash" 
temperature = 0.3
max_output_tokens = 3000

[llm_models.information_summary]
provider = "gemini"
model_name = "gemini-2.0-flash"
temperature = 0.8
max_output_tokens = 1000

[llm_models.embedding_default]
provider = "SILICONFLOW"
model_name = "BAAI/bge-m3"

# -----------------------------------------------------------------------------
# 网络代理配置
# -----------------------------------------------------------------------------
[proxy]
use_proxy = true
# 如果 use_proxy = true，代码会尝试从 http_proxy_url 解析 host 和 port,
# 如果 http_proxy_url 为空或无效，则可能尝试从环境变量 PROXY_HOST 和 PROXY_PORT 读取。
# 这个逻辑需要在代码中确认和调整。
http_proxy_url = "" # 例如 "http://127.0.0.1:7890"


# -----------------------------------------------------------------------------
# 应用核心逻辑 ("意识流") 设置
# -----------------------------------------------------------------------------
[core_logic_settings]
thinking_interval_seconds = 30

# -----------------------------------------------------------------------------
# "侵入性思维" 模块设置
# -----------------------------------------------------------------------------
[intrusive_thoughts_module_settings]
enabled = true
generation_interval_seconds = 600
insertion_probability = 0.15